# Generated by Django 3.0.7 on 2020-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_granted',
            field=models.BooleanField(default=False),
        ),
    ]
